name: jewellery
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+3

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  firebase_auth: ^5.1.1
  carousel_slider: ^5.0.0
  get: ^4.6.6
  animated_text_kit: ^4.2.2
  firebase_core: ^3.3.0
  firebase_storage: ^12.1.0
  cloud_firestore: ^5.0.2
  image_picker: ^1.1.2
  fast_cached_network_image: ^1.2.9
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  photo_view: ^0.15.0
  share: ^2.0.4
  path_provider: ^2.1.3
  fluttertoast: ^8.2.6
  google_fonts: ^6.2.1
  http: ^1.2.1
  url_launcher: ^6.3.0
  flutter_spinkit: ^5.2.1
  shared_preferences: ^2.2.3
  logger: ^2.3.0
  font_awesome_flutter: ^10.7.0
  flutter_native_splash: ^2.4.1
  firebase_messaging: ^15.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
 
